language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/2.0.gemfile
      env: QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - rvm: 2.0.0
      gemfile: gemfiles/2.0.gemfile
      env: QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    - rvm: jruby-19mode
      gemfile: gemfiles/2.0.gemfile
      env: QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
notifications:
  email: false
script: xvfb-run rake
env:
  - QMAKE=/usr/bin/qmake
  - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
gemfile:
  - gemfiles/2.0.gemfile
  - gemfiles/2.1.gemfile
before_install:
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev qtlocation5-dev qtsensors5-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev qt4-default
install: bundle
